let
    Source = #date(2018, 1, 1),
    Custom1 = List.Dates(Source, Number.From(#date(2023, 1, 1))- Number.From(Source) ,#duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), type number),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Date]), type number),
    #"Quarter Name" = Table.AddColumn(#"Inserted Quarter", "QuarterName", each "Q" & Number.ToText([Quarter])),
    #"Inserted Month" = Table.AddColumn(#"Quarter Name", "Month", each Date.Month([Date]), type number),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "MonthName", each Date.MonthName([Date]), type text),
    #"Month Short" = Table.AddColumn(#"Inserted Month Name", "MonthShort", each Date.ToText([Date],"MMM")),
    MonthYear = Table.AddColumn(#"Month Short", "MonthYear", each Date.ToText([Date],"MMM yy")),
    #"Month Sort" = Table.AddColumn(MonthYear, "MonthYearSort", each Date.ToText([Date], "yyyyMM")),
    #"Inserted Day Name" = Table.AddColumn(#"Month Sort", "DayName", each Date.DayOfWeekName([Date]), type text),
    #"Day Name Short" = Table.AddColumn(#"Inserted Day Name", "DayNameShort", each Date.ToText([Date],"ddd")),
    #"Inserted Day of Week" = Table.AddColumn(#"Day Name Short", "DayOfWeek", each Date.DayOfWeek([Date],Day.Saturday), type number),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Day of Week", "WeekOfYear", each Date.WeekOfYear([Date]), type number),
    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Year", "StartOfWeek", each Date.StartOfWeek([Date],Day.Saturday), type date),
    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "EndOfWeek", each Date.EndOfWeek([Date],Day.Saturday), type date)
in
    #"Inserted End of Week"